image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  stage: test
  script:
    - 'dotnet test --no-restore --logger:"junit;LogFilePath=$CI_PROJECT_DIR/test-result.xml"'
  artifacts:
    reports:
      junit: test-result.xml

.publish: &publish
  stage: deploy
  script:
    - 'dotnet publish -r ${RID} -o deacc_publish_${RID} --self-contained -p:PublishSingleFile=true DeACC/DeACC.csproj'
  artifacts:
    expire_in: 1 week
    paths:
      - deacc_publish_${RID}/*

publish win-x64:
  <<: *publish
  variables:
    RID: win-x64

publish linux-x64:
  <<: *publish
  variables:
    RID: linux-x64

publish osx-x64:
  <<: *publish
  variables:
    RID: osx-x64

publish osx-arm64:
  <<: *publish
  variables:
    RID: osx-arm64
