namespace DeACC
{
    /// <summary>
    /// ACS built-in functions.
    /// Literally just the ACSF_ enum from p_acs.cpp in ZDoom/Zan source with the ACSF_ prefix removed.
    /// </summary>
    internal enum AcsBuiltIn
    {
        GetLineUDMFInt = 1,
        GetLineUDMFFixed,
        GetThingUDMFInt,
        GetThingUDMFFixed,
        GetSectorUDMFInt,
        GetSectorUDMFFixed,
        GetSideUDMFInt,
        GetSideUDMFFixed,
        GetActorVelX,
        GetActorVelY,
        GetActorVelZ,
        SetActivator,
        SetActivatorToTarget,
        GetActorViewHeight,
        GetChar,
        GetAirSupply,
        SetAirSupply,
        SetSkyScrollSpeed,
        GetArmorType,
        SpawnSpotForced,
        SpawnSpotFacingForced,
        CheckActorProperty,
        SetActorVelocity,
        SetUserVariable,
        GetUserVariable,
        Radius_Quake2,
        CheckActorClass,
        SetUserArray,
        GetUserArray,
        SoundSequenceOnActor,
        SoundSequenceOnSector,
        SoundSequenceOnPolyobj,
        GetPolyobjX,
        GetPolyobjY,
        CheckSight,
        SpawnForced,
        AnnouncerSound,    // Skulltag
        SetPointer,
        ACS_NamedExecute,
        ACS_NamedSuspend,
        ACS_NamedTerminate,
        ACS_NamedLockedExecute,
        ACS_NamedLockedExecuteDoor,
        ACS_NamedExecuteWithResult,
        ACS_NamedExecuteAlways,
        UniqueTID,
        IsTIDUsed,
        Sqrt,
        FixedSqrt,
        VectorLength,
        SetHUDClipRect,
        SetHUDWrapWidth,
        SetCVar,
        GetUserCVar,
        SetUserCVar,
        GetCVarString,
        SetCVarString,
        GetUserCVarString,
        SetUserCVarString,
        LineAttack,
        PlaySound,
        StopSound,
        strcmp,
        stricmp,
        StrLeft,
        StrRight,
        StrMid,
        GetActorClass,
        GetWeapon,
        SoundVolume,
        PlayActorSound,
        SpawnDecal,
        CheckFont,
        DropItem,
        CheckFlag,
        SetLineActivation,
        GetLineActivation,
        GetActorPowerupTics,
        ChangeActorAngle,
        ChangeActorPitch,      // 80
        GetArmorInfo,
        DropInventory,
        PickActor,
        IsPointerEqual,
        CanRaiseActor,
        SetActorTeleFog,
        SwapActorTeleFog,
        SetActorRoll,
        ChangeActorRoll,
        GetActorRoll,
        QuakeEx,
        Warp,
        GetMaxInventory,
        SetSectorDamage,
        SetSectorTerrain,
        SpawnParticle,
        SetMusicVolume,
        CheckProximity,
        CheckActorState,

        // [BB] Skulltag functions
        ResetMap = 100,
        PlayerIsSpectator,
        ConsolePlayerNumber,
        GetTeamProperty, // [Dusk]
        GetPlayerLivesLeft,
        SetPlayerLivesLeft,
        ForceToSpectate,
        GetGamemodeState,
        SetDBEntry,
        GetDBEntry,
        SetDBEntryString,
        GetDBEntryString,
        IncrementDBEntry,
        PlayerIsLoggedIn,
        GetPlayerAccountName,
        SortDBEntries,
        CountDBResults,
        FreeDBResults,
        GetDBResultKeyString,
        GetDBResultValueString,
        GetDBResultValue,
        GetDBEntryRank,
        RequestScriptPuke,
        BeginDBTransaction,
        EndDBTransaction,
        GetDBEntries,
        NamedRequestScriptPuke,
        SystemTime,
        GetTimeProperty,
        Strftime,
        SetDeadSpectator,
        SetActivatorToPlayer,
        SetCurrentGamemode,
        GetCurrentGamemode,
        SetGamemodeLimit,
        SetPlayerClass,
        SetPlayerChasecam,
        GetPlayerChasecam,
        SetPlayerScore,
        GetPlayerScore,
        InDemoMode,
        SetActionScript,
        SetPredictableValue,
        GetPredictableValue,
        ExecuteClientScript,
        NamedExecuteClientScript,
        SendNetworkString,
        NamedSendNetworkString,
        GetChatMessage,
        GetMapRotationSize,
        GetMapRotationInfo,
        GetCurrentMapPosition,
        GetEventResult,
        GetActorSectorLocation,
        ChangeTeamScore,
        SetGameplaySetting,
        SetCustomPlayerValue,
        GetCustomPlayerValue,
        ResetCustomDataToDefault,
        LumpOpen,
        LumpRead,
        LumpReadString,
        LumpReadArrayLocal,
        LumpReadArrayModule,
        LumpReadArrayHub,
        LumpReadArrayGlobal,
        LumpGetInfo,
        LumpClose,
        Addbot,
        RemoveBot,
        OpenMenu,
        CloseMenu,
        BanFromGame,
        GetPlayerStatus,
        SetPlayerWeaponZoomFactor,
        SetPlayerSkin,
        GetPlayerSkin,
        GetPlayerCountry,
        SetNextMapPosition,
        GivePlayerMedal,
        GetPlayerJoinQueuePosition,
        SkipJoinQueue,
        GetControlPointInfo,
        SetControlPointInfo,
        GetSkinProperty,
        IsPlayerContestingControlPoint,

        // -1xx are reserved for Zandronum
        CheckClass = 200,
        DamageActor, // [arookas]
        SetActorFlag,
        SetTranslation,
        GetActorFloorTexture,
        GetActorFloorTerrain,
        StrArg,
        Floor,
        Round,
        Ceil,
        ScriptCall,	// ACS does not know varargs so use something large as maximum.
        StartSlideshow,
        GetSectorHealth,
        GetLineHealth,
        SetSubtitleNumber,
        GetNetID,
        SetActivatorByNetID,
        
        // Eternity's
        GetLineX = 300,
        GetLineY,
        SetAirFriction,
	
        // GZDoom OpenGL
        SetSectorGlow = 400,
        SetFogDensity,
        
        // ZDaemon
        GetTeamScore = 19620,  // (int team)
        SetTeamScore,			// (int team, int value)
    }
}
